version: '2'
services:
  wordpress:
    image: wordpress
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "80:80"
    links:
      - db
    logging:
      driver: awslogs
      options:
        awslogs-group: wordpress-dev1
        awslogs-region: us-east-2
        awslogs-stream-prefix: wordpress
  db:
    image: mysql
    cpu_shares: 100
    mem_limit: 524288000
    environment:
      MYSQL_ROOT_PASSWORD: password
    logging:
      driver: awslogs
      options:
        awslogs-group: mysql-dev1
        awslogs-region: us-east-2
        awslogs-stream-prefix: mysql
