version: '2'
services:
  wordpress:
    image: wordpress
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: devlogs1
        awslogs-region: us-east-2
        awslogs-stream-prefix: wordpress
